<?php
print '<div id="f1_main_content" class="rounded7 hidden" style="background: none;height: 480px; margin-top: 20px; padding-top: 0px;">
<div class="gen_header" style="border-bottom: 1px dotted grey;">
Contrat proposal...
</div>
<div id="left_content" class="fl" style="padding-left: 10px;margin-top: 10px;width: 100%;height: 480px;">
<div id="contentq" style="width: 98%; padding: 10px;">
<table width="100%" border="0" cellspacing="0" cellpadding="8" class="listing_table">
<tr>
<td valign="top"> Month</td>
<td valign="top">
  </td><td valign="top"></td><td valign="top"></td><td valign="top">
  <span></span><br /></td><td align="center" valign="top">				
  </td></tr>		
        
        <tr class="listing_header">
			<td width="20%">Freight</td>
			<td width="22%">Origin / Date</td>
			<td width="22%">Destination / Date</td>
			<td width="15%">Freight Holder</td>
			<td width="11%">Solde</td>
			<td width="10%" align="center">Status</td>
			</tr>
			<tr class="altrow2">
				<td valign="top">
				<span><strong>C</strong>D</span><br />	
                <span><strong>S</strong>D</span><br />
                <span><strong>D</strong>D</span><br />			
					
				</td>
				<td valign="top">
                <span><strong>C</strong>D</span><br />	
                <span><strong>S</strong>D</span><br />
                <span><strong>D</strong>D</span><br />
                    </td>
				<td valign="top">
			    <span><strong>C</strong>D</span><br />	
                <span><strong>S</strong>D</span><br />
                <span><strong>D</strong>D</span><br />
                </td>
				<td valign="top">
               <span><strong>C</strong>D</span><br />	
                <span><strong>S</strong>D</span><br />
                <span><strong>D</strong>D</span><br />			
               </td>
				<td valign="top">
				<span><strong>C</strong>Amount</span><br />	                  
               </td>
				<td align="center" valign="top">				
			<span>In process / Complete</span><br />	
					</td>
				</tr>
  <tr class="altrow2"><td valign="top">	</td><td valign="top">
  </td><td valign="top"></td><td valign="top"></td><td valign="top">
  <span>Complete</span><br /></td><td align="center" valign="top">				
  </td></tr>
  <tr style="border: none;">
<td valign="top"></td>
<td valign="top">
  </td><td valign="top"></td><td valign="top"></td><td valign="top">
  <span></span><br /></td><td align="center" valign="top">				
  Button Pay
  </td></tr>
</table>

</div>
</div>
    </div>';

?>