<?php
    print '<div id="f1_main_content" class="rounded7" style="background: none;height: 480px; margin-top: 20px; padding-top: 0px;">
<div class="gen_header" style="border-bottom: 1px dotted grey;">
Care about...
</div>
<div id="left_content" class="fl" style="padding-left: 10px;margin-top: 10px;width: 100%;height: 480px;">
<table style="width: 100%; color: black; font-size: 15pt;">';
Fm_User::__gET_TTR_ACCOUNT_ACTIVATION_REMAINDER_page($transpid);
print '
  </table>
</div>
    </div>';
?>