<?php 

print' <style type="text/css">
  /*Freightmeta loader based css */
.fmloader {
    position: fixed;
    top: 15%;
    width: 10%;
    height:20%;
    float: left;
    left: 15%;
    z-index: 5;
    }
.fmloader .wBall {position: absolute;width: 96px;
height: 96px;opacity: 0;-moz-transform: rotate(225deg);
-moz-animation: orbit 10.45s infinite;
-webkit-transform: rotate(225deg);
-webkit-animation: orbit 10.45s infinite;
-ms-transform: rotate(225deg);
-ms-animation: orbit 10.45s infinite;
-o-transform: rotate(225deg);
-o-animation: orbit 10.45s infinite;
transform: rotate(225deg);
animation: orbit 10.45s infinite;}
.fmloader .wBall .wInnerBall{position: absolute;width: 
11px;height: 11px;background: #5aa5cc;left:0px;top:0px;
-moz-border-radius: 11px;
-webkit-border-radius: 11px;
-ms-border-radius: 11px;
-o-border-radius: 11px;
border-radius: 11px;}.fmloader #wBall_1 {-moz-animation-delay: 2.28s;
-webkit-animation-delay: 2.28s;
-ms-animation-delay: 2.28s;
-o-animation-delay: 2.28s;
animation-delay: 2.28s;}
.fmloader #wBall_2 {-moz-animation-delay: 0.46s;
-webkit-animation-delay: 0.46s;
-ms-animation-delay: 0.46s;
-o-animation-delay: 0.46s;
animation-delay: 0.46s;}
.fmloader #wBall_3 {-moz-animation-delay: 0.91s;
-webkit-animation-delay: 0.91s;
-ms-animation-delay: 0.91s;
-o-animation-delay: 0.91s;
-delay: 0.91s;}
.fmloader #wBall_4 {-moz-animation-delay: 1.37s;
-webkit-animation-delay: 1.37s;
-ms-animation-delay: 1.37s;
-o-animation-delay: 1.37s;
animation-delay: 1.37s;}
.fmloader #wBall_5 {-moz-animation-delay: 1.82s;
-webkit-animation-delay: 1.82s;
-ms-animation-delay: 1.82s;
-o-animation-delay: 1.82s;
animation-delay: 1.82s;}
@-moz-keyframes orbit {
    0% {
    opacity: 1;z-index:99;
    -moz-transform: rotate(180deg);
    -moz-animation-timing-function: ease-out;}
    7% {opacity: 1;-moz-transform: rotate(300deg);
    -moz-animation-timing-function: linear;
    -moz-origin:0%;}30% {opacity: 1; 
    -moz-transform:rotate(410deg);
    -moz-animation-timing-function: ease-in-out;
    -moz-origin:7%;}39% {opacity: 1; 
    -moz-transform: rotate(645deg);
    -moz-animation-timing-function: linear;
    -moz-origin:30%;}70% {opacity: 1;
    -moz-transform: rotate(770deg);
    -moz-animation-timing-function: ease-out;
    -moz-origin:39%;}75% {opacity: 1; 
    -moz-transform: rotate(900deg);
    -moz-animation-timing-function: ease-out;
    -moz-origin:70%;}76% {opacity: 0;
    -moz-transform:rotate(900deg);}100% {opacity: 0;
    -moz-transform: rotate(900deg);}}
@-webkit-keyframes orbit {0% {opacity: 1;z-index:99;
-webkit-transform: rotate(180deg);
-webkit-animation-timing-function: ease-out;}7% {opacity: 1;
-webkit-transform: rotate(300deg);
-webkit-animation-timing-function: linear;
-webkit-origin:0%;}30% {opacity: 1; 
-webkit-transform:rotate(410deg);
-webkit-animation-timing-function: ease-in-out;
-webkit-origin:7%;}39% {opacity: 1; 
-webkit-transform: rotate(645deg);
-webkit-animation-timing-function: linear;
-webkit-origin:30%;}70% {opacity: 1;
-webkit-transform: rotate(770deg);
-webkit-animation-timing-function: ease-out;
-webkit-origin:39%;}75% {opacity: 1; 
-webkit-transform: rotate(900deg);
-webkit-animation-timing-function: ease-out;
-webkit-origin:70%;}76% {opacity: 0;
-webkit-transform:rotate(900deg);}100% {opacity: 0;
-webkit-transform: rotate(900deg);}}
@-ms-keyframes orbit {0% {opacity: 1;z-index:99;
-ms-transform: rotate(180deg);
-ms-animation-timing-function: ease-out;}7% {opacity: 1;
-ms-transform: rotate(300deg);
-ms-animation-timing-function: linear;
-ms-origin:0%;}30% {opacity: 1; 
-ms-transform:rotate(410deg);
-ms-animation-timing-function: ease-in-out;
-ms-origin:7%;}39% {opacity: 1; 
-ms-transform: rotate(645deg);
-ms-animation-timing-function: linear;
-ms-origin:30%;}70% {opacity: 1;
-ms-transform: rotate(770deg);
-ms-animation-timing-function: ease-out;
-ms-origin:39%;}75% {opacity: 1; 
-ms-transform: rotate(900deg);
-ms-animation-timing-function: ease-out;
-ms-origin:70%;}76% {opacity: 0;
-ms-transform:rotate(900deg);}
100% {opacity: 0;-ms-transform: rotate(900deg);}}
@-o-keyframes orbit {0% {opacity: 1;
z-index:99;
-o-transform: rotate(180deg);
-o-animation-timing-function: ease-out;}
7% {opacity: 1;-o-transform: rotate(300deg);
-o-animation-timing-function: linear;
-o-origin:0%;}30% {opacity: 1; 
-o-transform:rotate(410deg);
-o-animation-timing-function: ease-in-out;
-o-origin:7%;}39% {opacity: 1; 
-o-transform: rotate(645deg);
-o-animation-timing-function: linear;
-o-origin:30%;}70% {opacity: 1;
-o-transform: rotate(770deg);
-o-animation-timing-function: ease-out;
-o-origin:39%;}75% {opacity: 1; 
-o-transform: rotate(900deg);
-o-animation-timing-function: ease-out;
-o-origin:70%;}76% {opacity: 0;
-o-transform:rotate(900deg);}
100% {opacity: 0;-o-transform: rotate(900deg);}}
@keyframes orbit {0% {opacity: 1;
z-index:99;transform: rotate(180deg);
animation-timing-function: ease-out;}
7% {opacity: 1;transform: rotate(300deg);
animation-timing-function: linear;origin:0%;}
30% {opacity: 1; transform:rotate(410deg);
animation-timing-function: ease-in-out;
origin:7%;}39% {opacity: 1; 
transform: rotate(645deg);
animation-timing-function: linear;
origin:30%;}70% {opacity: 1;
transform: rotate(770deg);
animation-timing-function: ease-out;
origin:39%;}75% {opacity: 1; 
transform: rotate(900deg);
animation-timing-function: ease-out;
origin:70%;}76% {opacity: 0;
transform:rotate(900deg);}100% {opacity: 0;
transform: rotate(900deg);}}

        #fmCheck{
	display: block;
	width: 24px;
	height:24px;
	padding: 0px;
	background-repeat: no-repeat;
	background-position: center center;
	float: right; 
	margin: 5px;
    }
        #fmCheckm{
	display: block;
	width: 24px;
	height:24px;
	padding: 0px;
	background-repeat: no-repeat;
	background-position: center center;
	float: right; 
	margin: 5px;
    }
 .usernameLoading{
	background: url(../public/images/ajax-loader.gif) no-repeat;
}
.usernameFail{
    background: url(../public/images/no.png) no-repeat;
}
.usernamePassed{
background: url(../public/images/ok.png) no-repeat;
}

  </style>
  
  
  
  
  ';

print <<<script
 <script type="text/javascript">
	$(document).ready(function(){
		 var fmCheck = $('#fmCheck');
		$('.fmusrnm').on('keyup', function(){
			var username = $('.fmusrnm').val();
			if (username.length >= 3) {
				$.ajax({
				    url:'ajax.check.usrnm.php',
					type: 'POST',
					cache: 'false',
					data: 'username='+username, // form data
					beforeSend: function() {
						// show loading image
						fmCheck.attr('class', 'usernameLoading');
					},
					success: function(d) {
						console.log(d)
						if (d == 200) {
							// show ok image
							fmCheck.attr('class', 'usernamePassed');
						}
						else if (d == 201) {
							// show fail image
							fmCheck.attr('class', 'usernameFail');
                            $('.notefail').removeClass('hidden');
                            $('.notefail').css('border','2px solid red');
                            $('.notefail').html('Username already used! Please, perform another');
                            
                            setInterval(function()
                      {  $('.notefail').addClass('hidden');  
                      }   ,3000);
                            
						}
					}
				});
			};
		});
	});
	</script>

<script type="text/javascript">
	$(document).ready(function(){
		 var fmCheck = $('#fmCheckm');
		$('.fmmail').on('keyup', function(){
			var mail = $('.fmmail').val();
			if (mail.length >= 3) {
				$.ajax({
				    url:'ajax.check.mail.php',
					type: 'POST',
					cache: 'false',
					data: 'usermail='+mail, // form data
					beforeSend: function() {
						// show loading image
						fmCheck.attr('class', 'usernameLoading');
					},
					success: function(d) {
						console.log(d)
						if (d == 300) {
							// show ok image
							fmCheck.attr('class', 'usernamePassed');
						}
						else if (d == 301) {
							// show fail image
							fmCheck.attr('class', 'usernameFail');
                            $('.notmail').css('border','2px solid red');
                            $('.notmail').html('E-mail already used! Please, perform another');
						}
					}
				});
			};
		});
	});
	</script>

script;
?>