<style>
a{
    color:#F3F3F3
}
</style>

<div class="fl header_option">
<div class="fl"><a href="usr-sms.php">Messages</a></div>
<div style="margin-left:2px; float:fl; padding:0px 3px 0px 2px; background-color:#FF6633; color:white; font-weight:normal;" class="rounded5"><a href="/messages.php?display=unread" style="color:white;">1 Unread</a></div>
</div> 
</div>
<div class="outerbox column rounded" style="float: left; width: 220px; height: 700px;">
<div style="margin:10px;"><div style="margin-bottom:5px;">
<div style="float:left; margin-right:5px;"><img src="images/cust/down.png"/></div>
<div style="font-size:13px;padding-top:1px;"><strong>My Inbox</strong></div>
<div class="clear"></div></div>
<div class="leftsection innerbox rounded" style="font-size: 8pt;">
<div class="leftsection-option">
<div class="leftsection-icon"><img src="images/cust/email2.png"/></div><a class="fz" href="usr-sms.php?display=unread">Unread</a> (1)
<div class="clear"></div>
</div>
<div class="leftsection-option">
<div class="leftsection-icon"><img src="images/cust/mail-open.png"/></div><a class="fz" href="usr-sms.php?display=read">Read</a> (0)
<div class="clear"></div>
</div>
<div>
<div class="leftsection-icon"><img src="images/cust/Folder.png"/></div><a class="fz" href="usr-sms.php?display=archived">Archived</a> (0)
<div class="clear"></div>
</div></div>

<div style="margin-bottom:5px;">
<div style="float:left; margin-right:5px;"><img src="images/cust/down.png"/></div>
<div style="font-size:13px;padding-top:1px;"><strong>My Freight Listings</strong></div>
<div class="clear"></div>
</div>
<div class="leftsection innerbox rounded">
<div class="leftsection-option">
<div class="leftsection-icon"><img src="images/cust/txt.png"/></div><a class="fz"  href="user-freight.php?status=Active">Active</a> (1)
<div class="clear"></div>
</div>
<div class="leftsection-option">
<div class="leftsection-icon"><img src="images/cust/txt.png"/></div><a class="fz" href="user-freight.php?status=Booked">Booked</a> (0)
<div class="clear"></div>
</div>
<div class="leftsection-option">
<div class="leftsection-icon"><img src="images/cust/txt.png"/></div><a class="fz" href="user-freight.php?status=Expired">Expired</a> (0)
<div class="clear"></div>
</div>
<div class="leftsection-option">
<div class="leftsection-icon"><img src="images/cust/txt.png"/></div><a class="fz" href="user-freight.php?status=Cancelled">Cancelled</a> (0)
<div class="clear"></div>
</div><div>
<div class="leftsection-icon"><img src="images/cust/icon_add.png"/></div><a class="fz11bold" href="add_freight.php?new">List Freight</a>
<div class="clear"></div>
</div></div>
<div style="margin-bottom:5px;"><div style="float:left; margin-right:5px;"><img src="images/cust/down.png"/></div>
<div style="font-size:13px;padding-top:1px;"><strong>My Bookings</strong></div>
<div class="clear"></div>
</div>
<div class="leftsection innerbox rounded">
<div class="leftsection-option">
<div class="leftsection-icon"><img src="images/cust/delivery.png"/></div><a class="fz" href="u_booked_freight.php?status=booked">Booked</a> (0)
<div class="clear"></div>
</div>
<div class="leftsection-option">
<div class="leftsection-icon"><img src="images/cust/delivery.png"/></div><a class="fz" href="u_booked_freight.php?status=complete">Completed</a> (0)
<div class="clear"></div>
</div><div>
<div class="leftsection-icon"><img src="images/cust/delivery.png"/></div><a class="fz" href="u_booked_freight.php?status=cancelled">Cancelled</a> (0)
<div class="clear"></div>
</div></div>

<div style="margin-bottom:5px;"><div style="float:left; margin-right:5px;"><img src="images/cust/down.png"/></div>
<div style="font-size:13px;padding-top:1px;"><strong>My Account</strong></div>
<div class="clear"></div>
</div>
<div class="leftsection innerbox rounded">
<div class="leftsection-option">
<div class="leftsection-icon"><img src="images/cust/edit.png"/></div><a class="fz"  href="u_pf_update.php">Update Account Details</a>
<div class="clear"></div>
</div>
<div><div class="leftsection-icon">
<img src="images/cust/edit.png"/>
</div><a class="fz"  href="u_pwd_change.php">Change Password</a>
<div class="clear"></div>
</div>
</div>
<div style="margin-bottom:5px;"><div style="float:left; margin-right:5px;"><img src="images/cust/down.png"/></div>
<div style="font-size:13px;padding-top:1px;"><strong>Requestes</strong></div>
<div class="clear"></div>
</div>
<div class="leftsection innerbox rounded">
<div class="leftsection-option">
<div class="leftsection-icon"><img src="images/cust/evaluate.png"/></div><a class="fz" href="t.evaluation.php?fid='..'&sid='..'">Evaluate transporter</a>
<div class="clear"></div>
</div>
<div class="leftsection-option">
<div class="leftsection-icon"><img src="images/cust/evaluate.png"/></div><a class="fz" href="answers_freight.php?fid='..'&sid='..'">Answers to a Question</a>
<div class="clear"></div>
</div>
<div class="leftsection-option" style="border: none;">
<div class="leftsection-icon"><img src="images/cust/contrat.png"/></div><a class="fz" href="fm_contrat.php?fid='..'&sid='..'">Build contrat</a>
<div class="clear"></div>
</div>
</div>

<br/>
</div>
</div>